language: android

jdk:
  - openjdk8

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - ".+"

before_install:
  - mkdir -p "$ANDROID_HOME/licenses/"
  - curl "https://download.msfjarvis.website/.viscerion/sdk-licenses.tar.xz" | tar -C "$ANDROID_HOME/licenses/" --strip-components=1 -xvf -

script:
  - "./gradlew clean build test lintDebug -Dpre-dex=false"

notifications:
  email: false

sudo: false

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - "$ANDROID_HOME"
